[project]
name = "sbremote-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "humanize>=4.13.0",
    "inquirer>=3.4.1",
    "pyatv>=0.16.1",
    "sponsorblock>=0.1.3",
    "yaspin>=3.1.0",
    "yt-dlp>=2025.8.27",
]
